#! /bin/bash

get=$(powerprofilesctl get)-profile

action=$(yad --width 310 --window-icon=gnome-power-manager --entry --title "Power Profile Switcher" \
    --image=gnome-power-manager \
    --button=" Switch:0" --button=" Quit" \
    --text "Currently using: $get \ Change to your preferred profile:" \
    --entry-text \
    " Balanced" " Power-Saver" " Performance")
ret=$?

[[ $ret -eq 1 ]] && exit 0

if [[ $ret -eq 2 ]]; then
    gdmflexiserver --startnew &
    exit 0
fi

case $action in
    *) cmd="powerprofilesctl set balanced & notify-send -t 5000 -i power-profile-balanced-symbolic 'Switched to balanced profile'" ;;
    *) cmd="powerprofilesctl set power-saver & notify-send -t 5000  -i power-profile-power-saver-symbolic 'Switched to power-saver profile'" ;;
    *) cmd="powerprofilesctl set performance & notify-send -t 5000 -i power-profile-performance-symbolic 'Switched to performance profile'" ;;
    *) exit 1 ;;    
esac

eval exec $cmd



